### ISSUE TITLE
Recent builds of Stockfish significantly weaker than previous builds

### ISSUE THREAD

**Issue by Zandon21** [mcostalba/Stockfish#261]
Hi,

See https://docs.google.com/document/d/1esFjhk-URKXvZbZrb-h6MElCinXbpRmTbOGBYYprfKQ/pub

It seems that rather than getting stronger, Stockfish is getting weak!

**Comment by mcostalba** [comment]
Please stop spamming issue list, eventually use the forum for these kind of comments. I close it now.
