### ISSUE TITLE
Tempo Set-up

### ISSUE THREAD

**Issue by LonelyGM** [mcostalba/Stockfish#267]
stage = PROBCUT;

  // In ProbCut we generate only captures that are better than the parent's
  // captured piece.
  captureThreshold = PieceValue[MG][pt];
  ttMove = (ttm && pos.pseudo_legal(ttm) ? ttm : MOVE_NONE);

  if (ttMove && (!pos.capture(ttMove) || pos.see(ttMove) <= captureThreshold))
      ttMove = MOVE_NONE;

  end += (ttMove != MOVE_NONE);
}

I think the reason why Stockfish is getting "weaker" are these kinds of functions.

**Comment by mcostalba** [comment]
Please stop spamming issue list, eventually use the forum for these kind of comments. I close it now.
